/**
 * KCL Project Generator
 *
 * Generates KCL (KittyCAD Language) assembly code that imports child
 * STEP files and applies translate/rotate transforms to position them.
 */

import type { AssemblyPlan } from './types'

export interface KclProject {
  mainKcl: string
  files: Array<{ name: string; content: string }>
}

/**
 * Generate a KCL project from an assembly plan.
 *
 * The generated main.kcl imports each child STEP file and applies
 * the computed transforms. For qty > 1, uses the pattern() function.
 */
export function generateKclProject(plan: AssemblyPlan): KclProject {
  const lines: Array<string> = []

  lines.push(`// Assembly: ${plan.assemblyTempId}`)
  lines.push(`// Auto-generated by Cascadia Design Engine`)
  lines.push(`// ${plan.reasoning}`)
  lines.push('')

  // If LLM provided KCL code directly, use it
  if (plan.kclCode && plan.kclCode.trim().length > 0) {
    return {
      mainKcl: plan.kclCode,
      files: [{ name: 'main.kcl', content: plan.kclCode }],
    }
  }

  // Otherwise, generate from placements
  for (const placement of plan.placements) {
    const varName = sanitizeVarName(placement.partName)
    const { translation: t, rotation: r } = placement.transform

    // Import STEP file
    lines.push(`let ${varName} = import("${placement.stepFileKey}")`)

    // Apply rotation if non-zero
    if (r.x !== 0 || r.y !== 0 || r.z !== 0) {
      if (r.x !== 0) {
        lines.push(`  |> rotateX(${r.x}, %)`)
      }
      if (r.y !== 0) {
        lines.push(`  |> rotateY(${r.y}, %)`)
      }
      if (r.z !== 0) {
        lines.push(`  |> rotateZ(${r.z}, %)`)
      }
    }

    // Apply translation if non-zero
    if (t.x !== 0 || t.y !== 0 || t.z !== 0) {
      lines.push(`  |> translate([${t.x}, ${t.y}, ${t.z}], %)`)
    }

    // Handle quantity > 1
    if (placement.quantity > 1) {
      lines.push('')
      lines.push(`// ${placement.partName} x${placement.quantity}`)
      for (let i = 1; i < placement.quantity; i++) {
        const cloneName = `${varName}_${i + 1}`
        lines.push(`let ${cloneName} = clone(${varName})`)
      }
    }

    lines.push('')
  }

  const mainKcl = lines.join('\n')

  return {
    mainKcl,
    files: [{ name: 'main.kcl', content: mainKcl }],
  }
}

/**
 * Sanitize a part name to be a valid KCL variable name.
 */
function sanitizeVarName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^[0-9]/, '_$&')
    .replace(/__+/g, '_')
    .toLowerCase()
}
