// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Cascadia PLM LLC

import { and, asc, count, desc, eq, ilike, or } from 'drizzle-orm'
import { alias } from 'drizzle-orm/pg-core'
import { LifecycleService } from './LifecycleService'
import { WorkOrderInstructionService } from './WorkOrderInstructionService'
import type {
  WorkOrder,
  WorkOrderCreateInput,
  WorkOrderStatus,
  WorkOrderUpdateInput,
} from '@/lib/items/types/work-order'
import { db } from '@/lib/db'
import { items, programs, workOrders } from '@/lib/db/schema'
import { NotFoundError } from '@/lib/errors'
import { ItemService } from '@/lib/items/services/ItemService'

/**
 * Work orders are items since Phase 2.5 (itemNumber = WO number,
 * items.state = status). This service is a facade over ItemService that
 * preserves the legacy API shape (workOrderNumber, status, createdAt, …)
 * so routes and UI keep working unchanged.
 */

// The part an order builds is a second join against items — alias it.
const partItems = alias(items, 'wo_part_items')

const legacyShape = (row: {
  item: typeof items.$inferSelect
  workOrder: typeof workOrders.$inferSelect
  partItemNumber?: string | null
  partName?: string | null
  partRevision?: string | null
  programName?: string | null
}): WorkOrder => ({
  id: row.item.id,
  workOrderNumber: row.item.itemNumber,
  status: row.item.state as WorkOrderStatus,
  partId: row.workOrder.partId,
  quantity: row.workOrder.quantity,
  quantityCompleted: row.workOrder.quantityCompleted,
  priority: row.workOrder.priority as WorkOrder['priority'],
  dueDate: row.workOrder.dueDate,
  customerOrder: row.workOrder.customerOrder,
  notes: row.workOrder.notes,
  assignedTo: row.workOrder.assignedTo ?? [],
  programId: row.workOrder.programId,
  requiresSignOff: row.workOrder.requiresSignOff,
  completedAt: row.workOrder.completedAt,
  createdAt: row.item.createdAt,
  createdBy: row.item.createdBy,
  modifiedAt: row.item.modifiedAt,
  modifiedBy: row.item.modifiedBy,
  part: row.partItemNumber
    ? {
        id: row.workOrder.partId!,
        itemNumber: row.partItemNumber,
        name: row.partName,
        revision: row.partRevision ?? '',
      }
    : null,
  program:
    row.programName && row.workOrder.programId
      ? { id: row.workOrder.programId, name: row.programName }
      : null,
})

export class WorkOrderService {
  static async create(
    data: WorkOrderCreateInput,
    userId: string,
  ): Promise<WorkOrder> {
    const created = await ItemService.create(
      'WorkOrder',
      {
        itemType: 'WorkOrder',
        revision: 'A',
        // itemNumber auto-generated by the WO-###### numbering scheme
        name: data.customerOrder ?? undefined,
        state: 'Not Started',
        partId: data.partId,
        quantity: data.quantity,
        priority: data.priority,
        dueDate: data.dueDate,
        customerOrder: data.customerOrder,
        notes: data.notes,
        assignedTo: data.assignedTo,
        programId: data.programId,
        requiresSignOff: data.requiresSignOff,
      } as never,
      userId,
    )
    const workOrder = await this.findById((created as { id?: string }).id!)
    return workOrder!
  }

  static async findById(id: string): Promise<WorkOrder | null> {
    const results = await db
      .select({
        item: items,
        workOrder: workOrders,
        partItemNumber: partItems.itemNumber,
        partName: partItems.name,
        partRevision: partItems.revision,
        programName: programs.name,
      })
      .from(workOrders)
      .innerJoin(items, eq(workOrders.itemId, items.id))
      .leftJoin(partItems, eq(workOrders.partId, partItems.id))
      .leftJoin(programs, eq(workOrders.programId, programs.id))
      .where(eq(workOrders.itemId, id))

    const row = results[0]
    if (!row) return null
    return legacyShape(row)
  }

  static async update(
    id: string,
    data: WorkOrderUpdateInput,
    userId: string,
  ): Promise<WorkOrder> {
    const existing = await this.findById(id)
    if (!existing) throw new NotFoundError('Work Order', id)

    await ItemService.update(
      id,
      {
        ...(data.customerOrder !== undefined && {
          name: data.customerOrder ?? undefined,
        }),
        ...data,
      },
      userId,
    )

    const updated = await this.findById(id)
    return updated!
  }

  static async delete(id: string, userId: string): Promise<void> {
    const existing = await this.findById(id)
    if (!existing) throw new NotFoundError('Work Order', id)
    await ItemService.delete(id, userId)
  }

  static async search(criteria: {
    status?: string
    partId?: string
    search?: string
    programId?: string
    limit?: number
    offset?: number
    sortBy?: string
    sortDir?: 'asc' | 'desc'
  }) {
    const conditions = [eq(items.itemType, 'WorkOrder')]

    if (criteria.status) {
      conditions.push(eq(items.state, criteria.status))
    }
    if (criteria.partId) {
      conditions.push(eq(workOrders.partId, criteria.partId))
    }
    if (criteria.programId) {
      conditions.push(eq(workOrders.programId, criteria.programId))
    }
    if (criteria.search) {
      conditions.push(
        or(
          ilike(items.itemNumber, `%${criteria.search}%`),
          ilike(workOrders.customerOrder, `%${criteria.search}%`),
        )!,
      )
    }

    const whereClause = and(...conditions)
    const limit = criteria.limit ?? 50
    const offset = criteria.offset ?? 0

    const [results, totalResult] = await Promise.all([
      db
        .select({
          item: items,
          workOrder: workOrders,
          partItemNumber: partItems.itemNumber,
          partName: partItems.name,
          partRevision: partItems.revision,
          programName: programs.name,
        })
        .from(workOrders)
        .innerJoin(items, eq(workOrders.itemId, items.id))
        .leftJoin(partItems, eq(workOrders.partId, partItems.id))
        .leftJoin(programs, eq(workOrders.programId, programs.id))
        .where(whereClause)
        .orderBy(
          criteria.sortBy === 'dueDate'
            ? criteria.sortDir === 'asc'
              ? asc(workOrders.dueDate)
              : desc(workOrders.dueDate)
            : criteria.sortBy === 'status'
              ? criteria.sortDir === 'asc'
                ? asc(items.state)
                : desc(items.state)
              : desc(items.createdAt),
        )
        .limit(limit)
        .offset(offset),
      db
        .select({ count: count() })
        .from(workOrders)
        .innerJoin(items, eq(workOrders.itemId, items.id))
        .where(whereClause),
    ])

    return {
      workOrders: results.map(legacyShape),
      total: totalResult[0]?.count ?? 0,
    }
  }

  static async updateStatus(
    id: string,
    newStatus: WorkOrderStatus,
    userId: string,
  ): Promise<WorkOrder> {
    const current = await this.findById(id)
    if (!current) throw new NotFoundError('Work Order', id)

    // The traveler gates completion: every non-skipped instruction line
    // must be complete (or explicitly skipped with a reason) first.
    if (newStatus === 'Complete') {
      await WorkOrderInstructionService.assertReadyForCompletion(id)
    }

    // Sanctioned Free-lifecycle write path (remediation WI-2.1/2.2): the
    // seeded WO lifecycle enforces Not Started → In Progress → Complete /
    // Cancelled, so no hand-rolled transition map here.
    await LifecycleService.transitionFreeItem(id, newStatus, userId)

    if (newStatus === 'Complete') {
      // completedAt is a work_orders type field, not lifecycle-controlled.
      await ItemService.update(id, { completedAt: new Date() } as never, userId)
    }

    const updated = await this.findById(id)
    return updated!
  }
}
